### ISSUE TITLE
Link to library docs in project page

### ISSUE THREAD

**Issue by vadimdemedes** [vdemedes/ohcrash-app#17]

**Comment by sindresorhus** [comment]
I meant on the project page (https://ohcrash.com/projects/unicorn), but could be useful here too.

**Comment by vadimdemedes** [comment]
Oh, that's what I wanted, I just typed the wrong title. Thanks for spotting this!

**Comment by vadimdemedes** [comment]
Done:

<img width="652" alt="screen shot 2016-01-24 at 12 02 57 am" src="https://cloud.githubusercontent.com/assets/697676/12533353/da9fe00a-c22d-11e5-9e7d-f94f1d273576.png">
