### ISSUE TITLE
Repos not showing

### ISSUE THREAD

**Issue by AdriVanHoudt** [vdemedes/ohcrash-app#23]
I had it on mobile first but also on laptop.

I get an error on https://github.com/vdemedes/ohcrash-app/blob/master/lib/github.js#L21

``` js
app.js:1285 Uncaught (in promise) TypeError: Cannot read property 'next' of null
    at https://ohcrash.com/app.js:1285:12
```

The call to `https://api.github.com/user/repos?type=owner` is successful and it returns all the repos but it has no link header

**Comment by vadimdemedes** [comment]
Thank you for reporting this! Fixing now.

**Comment by AdriVanHoudt** [comment]
np!

**Comment by vadimdemedes** [comment]
Fix deployed, could you please confirm it's working now?

**Comment by AdriVanHoudt** [comment]
yes works now, nice touch by adding the fork indicator!

**Comment by vadimdemedes** [comment]
Thanks, all the props go to Sindre Sorhus for that idea :)
