### ISSUE TITLE
Aggregation of issue possible ? | Question

### ISSUE THREAD

**Issue by ghost** [vdemedes/ohcrash-app#29]
What happens in case that 
`require('ohcrash')('api key', {
    exit: false
})` 
is one of the settings and over the night i got tons of the same exceptions , does OhCrash will open on my repo tons of issues as well ?

**Comment by vadimdemedes** [comment]
Hey, sorry to say this, but OhCrash is not maintained at the moment, due to the lack of time.

Consider using BugSnag or Sentry, which are much more mature and stable. Thanks for trying out OhCrash, I hope I will renovate it soon!
